apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: radito3/ss-notification-service:1.0.0
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /public/ping
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: private-key-volume
              mountPath: "/etc/private-key"
              readOnly: true
      volumes:
        - name: private-key-volume
          secret:
            secretName: creds-encryption-key
