apiVersion: v1
kind: Namespace
metadata:
  name: public
  labels:
    name: public
---
apiVersion: v1
kind: Namespace
metadata:
  name: hub
  labels:
    name: hub
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml-analysis
  labels:
    name: ml-analysis
