apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-traffic
  namespace: ml-analysis
spec:
  podSelector:
    matchLabels:
      app: ml-analysis
  policyTypes:
  - Ingress
  - Egress
  ingress: []
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: hub-ns
    ports:
    - protocol: TCP
      port: 8554
    - protocol: TCP
      port: 1935
    - protocol: UDP
      port: 8000
    - protocol: UDP
      port: 8001
