apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - serviceaccount.yml
  - statefulset.yml
  - rolebinding.yml
  - rbac.yml
  - lb-service.yaml
  - headless-service.yaml
