apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yml
  - statefulset.yml
  - rolebinding.yml
  - rbac.yml
  - lb-service.yaml
  - headless-service.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml

configMapGenerator:
  - name: mediamtx-config
    namespace: hub
    options:
      disableNameSuffixHash: true
    files:
      - mediamtx.yml
