apiVersion: v1
kind: Service
metadata:
  name: mediamtx
  namespace: hub
spec:
  type: LoadBalancer
  selector:
    app: mediamtx
  ports:
    - port: 8000
      targetPort: 8000
      name: rtp
      protocol: UDP
    - port: 8001
      targetPort: 8001
      name: rtcp
      protocol: UDP
    - port: 8554
      targetPort: 8554
      name: rtsp
    - port: 1935
      targetPort: 1935
      name: rtmp
    - port: 8888
      targetPort: 8888
      name: hls
    - port: 8889
      targetPort: 8889
      name: webrtc
    - port: 8080
      targetPort: 8080
      name: proxy
