apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mediamtx-role
rules:
# TODO: 
# - deployments: get, list, create
# - statefulsets: get, list
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
