apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mediamtx-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "delete"]

  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete"]

  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list"]
