apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mediamtx-hub-access
  namespace: hub
subjects:
  - kind: ServiceAccount
    name: mediamtx-serviceaccount
    namespace: hub
roleRef:
  kind: Role
  name: mediamtx-hub-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mediamtx-ml-analysis-access
  namespace: ml-analysis
subjects:
  - kind: ServiceAccount
    name: mediamtx-serviceaccount
    namespace: hub
roleRef:
  kind: Role
  name: mediamtx-ml-analysis-role
  apiGroup: rbac.authorization.k8s.io
