apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mediamtx
  namespace: hub
spec:
  serviceName: "mediamtx-headless"
  replicas: 3
  selector:
    matchLabels:
      app: mediamtx
  template:
    metadata:
      labels:
        app: mediamtx
    spec:
      containers:
      - name: mediamtx-container
        image: bluenviron/mediamtx:latest-ffmpeg
        ports:
        - containerPort: 8000 # RTP/UDP
        - containerPort: 8001 # RTCP/UDP
        - containerPort: 8554 # RTSP/TCP
        - containerPort: 1935 # RTMP
        - containerPort: 8888 # HLS
        - containerPort: 8889 # WebRTC
        # - containerPort: 8089
        # - containerPort: 8088
        # - containerPort: 9774
        volumeMounts:
        - name: mediamtx-config
          mountPath: /usr/etc/mediamtx.yml
          subPath: mediamtx.yml
          readOnly: true
      - name: mediamtx-proxy-container
        image: radito3/mediamtx-proxy:latest
        ports:
        - containerPort: 8080
      volumes:
      - name: mediamtx-config
        configMap:
          name: mediamtx-config
