apiVersion: batch/v1
kind: CronJob
metadata:
  # this won't be needed
  name: file-merger
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: file-merger
            image: ffmpeg:latest
            command: 
              - /bin/sh
              - -c
              - |
                head -n -1 file_log.txt > file_log_temp.txt && \
                ffmpeg -f concat -safe 0 -i file_log_temp.txt -c copy output_combined.mp4
            volumeMounts:
            - name: recordings
              mountPath: /
          restartPolicy: OnFailure
          volumes:
          - name: recordings
            hostPath: # this won't work, as the volume in the STS is an emptyDir
              path: /recordings
