apiVersion: v1
kind: Service
metadata:
  name: transcoder-service
spec:
  type: LoadBalancer
  selector:
    app: ffmpeg-transcoder
  ports:
    - name: rtmp
      port: 1935  # RTMP
      targetPort: 1935
    - name: hls
      port: 8080  # HLS and DASH
      targetPort: 8080
    - name: rtsp
      port: 8554  # RTSP
      targetPort: 8554
    - name: webrtc
      port: 8004  # WebRTC
      targetPort: 8004
