apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: public
spec:
  template:
    spec:
      containers:
      - name: ui-container
        image: my-custom-ui:latest # TODO: replace with built image
        env:
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              # kubectl create secret generic creds-encryption-key --from-file=private_key.pem -n your-namespace
              name: creds-encryption-key
              key: key
