apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: public
spec:
  template:
    spec:
      containers:
      - name: ui-container
        image: my-custom-ui:latest # TODO: replace with built image
        volumeMounts:
            - name: public-key-volume
              mountPath: "/usr/share/nginx/html/config"
              readOnly: true
      volumes:
        # kubectl create secret generic creds-encryption-key --from-file=private_key.pem -n your-namespace
        - name: public-key-volume
          secret:
            secretName: creds-encryption-key
