apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - network-policy.yaml

secretGenerator:
  - name: creds-encryption-key
    namespace: public
    type: Opaque
    options:
      disableNameSuffixHash: true
    files:
      - public_key.pem
