apiVersion: v1
kind: Service
metadata:
  name: web-ui
  namespace: public
spec:
  type: LoadBalancer # NodePort for dev
  selector:
    app: ui
  ports:
    - port: 80 # 4201 for dev
      targetPort: 80
